{
    name: Switch_Rational_Relu,
    #  magma settings
    from_checkpoint: False, 
    # dtype: float32,
    perceiver: False,

    # image encoder settings
    encoder_name: 'clip_resnet_large',
    freeze_img_encoder: False,
    rational_image_encoder: False,

    # adapter settings
    # adapter_config: {"mlp": {"adapter_type": "normal", "downsample_factor": 4}, "adapter_switch": True, "hidden_act": "rational:relu" },

    # train settings 
    batch_size: 4,
    train_steps: 500,
    lr: 1.0e-7,
    min_lr: 0.0,
    lr_decay_iters: 300000,
    image_enc_lr: 1.0e-7,
    use_image_embed_layernorm: true,
    image_embed_dropout_prob: 0.1, 
    image_size: 384,
    train_micro_batch_size_per_gpu: 1,
    
    gradient_accumulation_steps: 1,
    zero_stage: 2,
    gradient_clipping: 1.0,

    # dataset / save / load settings
    train_dataset_name: 'conceptual_captions',
    train_dataset_dir: '/home/ml-mmeuer/adaptable_magma/magma/datasets/coco_train_val',
    eval_dataset_name: 'coco',
    eval_dataset_dir: '/mnt/localdisk/coco_data',
    
    save: "/home/ml-mmeuer/magma/model_checkpoints/multimodal_transformer_rn50x16",
    load: "/mnt/shared_vol/checkpoints/multimodal_transformer_rn50x16",

    eval_every: 100,
}